version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: radio_schedules
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'radio'
    ports:
      - '3306:3306'
